### ISSUE TITLE
[Feature Request/Question] Converting Ketarin Packages to AU

### ISSUE THREAD

**Issue by zero77** [majkinetor/au#119]
Is there a way to convert ketarin packages to AU packages without recreating the whole package.
If not, can you please add support for this.
Thanks

**Comment by majkinetor** [comment]
No, this is not planned. I have never used Ketarin. There are several few features designed to make this easier ( AU wont complain on `{{ var }}` ) but thats it.


Its really not that hard to do it manually - I can convert ketarin to AU in less then 10 minutes without any other changes. AU `update.ps1` is generally changed on only few lines given the template. This means you can convert reasonably large repos within single day. 

The problem is when you have hundreds of packages but there are only few maintainers like that.

**Comment by majkinetor** [comment]
Also, given that coreteam-packages does not contain ketarin updaters any more its even less probable that somebody will do this.
