### ISSUE TITLE
Version compare broken when comparing pre version

### ISSUE THREAD

**Issue by riezebosch** [majkinetor/au#134]
```
nuspec version: 2.1.300-preview1-008174
remote version: 2.1.101
No new version found
```

Altough at [chocolatey-feed](https://chocolatey.org/packages/dotnetcore-sdk) it is considered a pre-release and the latest stable release is `2.1.4`.

This seems to work for me with docker-for-windows:
```
nuspec version: 17.12.0.15139
remote version: 17.12.0.15139
No new version found

nuspec version: 18.03.0.16433-edge
remote version: 18.03.0.16433-edge
No new version found
```

There it is actually comparing stable with stable and pre-release with pre-release. Maybe the double-dash gets into trouble?

**Comment by Thilas** [comment]
AU aims at updating a package only if a new version is found online. The way it is determined is by checking whether this remote version is greater than the nuspec one (i.e. the last packaged version). For that matter it uses the same logic than [semver](https://semver.org/spec/v1.0.0.html).

In your example, the remote version (`2.1.101`) is not greater than the nuspec one (`2.1.300-preview1-008174`):
- 2 = 2
- 1 = 1
- 101 < 300
Conclusion: remote version < nuspec version, therefore there is no new version found.

What you could do here is to use [streams](https://github.com/majkinetor/au#streams). If your package can have at the same time new prerelease versions and new stable versions, streams could help you. You'll find some examples of packages using streams in the documentation.

FYI, about docker-for-windows, it's working because you are talking about 2 different packages with 2 nuspec files each keeping its own version.

**Comment by riezebosch** [comment]
You're right! Though docker-for-windows share the same nuspec-id they both keep there own version and look to a different "channel" for updates. I confused the remote version for the chocolatey-feed version.
