### ISSUE TITLE
What are difference between using `Get-RemoteChecksum` in `au_BeforeUpdate` and `au_GetLatest`?

### ISSUE THREAD

**Issue by galeksandrp** [majkinetor/au#145]
What are more advised in case of undefault checksum retrieving?
* Pass `ChecksumFor none` to bypass `get_checksum` call, and then use `Get-RemoteChecksum` via `au_BeforeUpdate`?
* Use `Get-RemoteChecksum` in `au_GetLatest`?

**Comment by majkinetor** [comment]
`au_GetLatest` should be fast and shouldn't download large amounts of data generally. `au_BeforeUpdate` will download stuff only when needed (update actually happened).  If you used it exclusivelly in au_GetLatest your updateall procedure would be several times longer. 

So the second one is used only if you need exe locally to get the version from its metadata (checksum could be version on some tools too), otherwise, you shouldn't use it.
