### ISSUE TITLE
Kill hung threads in updateall

### ISSUE THREAD

**Issue by teknowledgist** [majkinetor/au#162]
I'm running into what appears to be a PowerShell bug in which `Invoke-WebRequest` hangs when certain elements are in the webpage.  The hang comes when I try to reference the `.links` property.  Many places that discuss it mention using the `-usebasicparsing` switch, but I am still seeing a hang on most (5 of 6) of my packages with GitHub as the information/download source.  The `rawcontent` is still available, but who wants to parse that?!

If I run the updates individually, I can see that they are hung and close them, but if I run `updateall`, it starts background processes that slowly start getting hung and the rate of updating packages slows in the visible console until it eventually stops progressing and the entire machine bogs down. 

I know there is some kind of timeout already, but is there any way to make it more robust?  It sometimes works, but often the hang is so bad, the timeout never kicks off.  I have to kill all the PowerShell processes manually.

I would love if someone has a way around the `Invoke-WebRequest` problem with GitHub pages too!  I can't be the only person experiencing this.

Thanks.

**Comment by majkinetor** [comment]
Its a known bug in iwr and probably fixed in v6. I reported it, the ticket is on MS user voice and probably here or on coreteam repo (cbb to find it).

There are number of other methods u can use to get the file from the Internet - curl, wget, etc. can all be used and are on the cinst-distance from having it where your AU jobs run.

**Comment by majkinetor** [comment]
BTW, updateall has option UpdateTimeout.
You can also manually implement this (as a function for example) in a manner:

start-job which-downloads
while(!timeout) { sleep 1 } else { kill-job }

**Comment by majkinetor** [comment]
Updateall timeout should work always, even in that case. You have to kill posh process in interactive session, I am 99% certain it doesn't happen on AV (judging from the fact that Github recently timeout because of this). 

I think this is specific to web server and/or its settings on remote side and thats why it can look random.

**Comment by majkinetor** [comment]
Notice, webclient timeout is not what I talk about, there is also that timeout in AU.

So, AU has 2 timeouts - webclient and overall update timeout. You should use later option for this error.

You cant use this when calling ./update.ps1 alone (outside the updateall scope). In such case, you need to use above mentioned options.

**Comment by majkinetor** [comment]
No problem m8. Information overload gets us all.
