### ISSUE TITLE
Cannot get gist to work

### ISSUE THREAD

**Issue by TraGicCode** [majkinetor/au#171]
Any ideas on what i might be doing wrong to constantly get this in my appveyor log?

https://ci.appveyor.com/project/TraGicCode/chocolatey-packages/builds/19318656
```

Running Gist
  ERROR:  
    {"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}
```

**Comment by majkinetor** [comment]
This usually happens when `gist_id` is not set but it seems in your case it is, maybe token is not right ?
Other thing that comes to mind is that you make sure token has gist access

Report is created and you can see it in AV artifacts.

You could troubleshout it by running plugin directly on iits own ([Gist.ps1](https://github.com/majkinetor/au/blob/master/AU/Plugins/Gist.ps1)), you can save report from build server locally and try to upload it by setting up parameters of the script directly. When you make it work from the local, it will work from AV.

PS: You also still use my mail address in av yaml.

**Comment by majkinetor** [comment]
Make sure to read this too:
https://github.com/majkinetor/au/blob/master/Plugins.md#gist

**Comment by TraGicCode** [comment]
It’s strange I did all of the instructions correct.  I’ll look again on Monday to see if I missed something minor.

**Comment by TraGicCode** [comment]
Hey @majkinetor ,

Running it locally works fine.  I think there is something i'm not doing correctly in the appveyor.yml in regards to the gist secret

**Comment by TraGicCode** [comment]
Is there an issue where appveyor doesn't handle encryped secrets for PR's?

**Comment by TraGicCode** [comment]
Yep the issue with with a PR
