### ISSUE TITLE
Q: stream versions in json?

### ISSUE THREAD

**Issue by OlafHaag** [majkinetor/au#200]
Hey! I need some clarificationon using streams. It concerns a [package](https://github.com/OlafHaag/chocolatey-packages/blob/master/automatic/jamovi/update.ps1) that has a stable stream and a pre-release stream as meta, install and portable packages. To mark the so-called current stream as pre-release, I add a *-current* to the version. And I use the Get-FixVersion helper from *Wormies-AU-Helpers* before that.

When the packageName.json is not present, the update causes 

> WARNING: Invalid nuspec file Version '' - using 0.0

When running the update it creates the json with following content:
```json
﻿{
    "current":  "1.1.7.0",
    "stable":  "1.0.7.0"
}
```

Running update with that json present, I get this:

> jamovi - checking updates using au version 2019.5.22                                        2 streams collected: stable current
> 
> *** Stream: current ***
> URL check
>   https://www.jamovi.org/downloads/jamovi-1.1.7.0-win64.zip
>   https://www.jamovi.org/downloads/jamovi-1.1.7.0-win64.exe
> nuspec version: 1.1.7.0
> remote version: 1.1.7.000-current
> No new version found
> 
> *** Stream: stable ***
> URL check
>   https://www.jamovi.org/downloads/jamovi-1.0.7.0-win64.zip
>   https://www.jamovi.org/downloads/jamovi-1.0.7.0-win64.exe
> nuspec version: 1.0.7.0
> remote version: 1.0.7.000
> No new version found
> 
> 
> Path          : D:\chocolatey-packages\automatic\jamovi
> Name          : jamovi
> Updated       : False
> Pushed        : False
> RemoteVersion : 1.0.7.000
> NuspecVersion : 1.0.7.0
> Result        : {jamovi - checking updates using au version 2019.5.22, , *** Stream:
>                 current ***, URL check...}
> Error         :
> NuspecPath    : D:\chocolatey-packages\automatic\jamovi\jamovi.nuspec
> NuspecXml     : #document
> Ignored       : False
> IgnoreMessage :
> StreamsPath   : D:\chocolatey-packages\automatic\jamovi\jamovi.json
> Streams       : {current, stable}

So it seems the version for the current stream in the json is wrong, because it should be the same as the nuspec (*1.1.7.000-current* instead of *1.1.7.0*).

How do I deal with that?
Could you tell me how to setup appveyor to also push the generated/changed json files back to the github repo? Or do I just have to push the json for each package once to make it push modifications upstream?

Thanks!

**Comment by AdmiringWorm** [comment]
Actually, from looking at your `update.ps1` file, the json is correct.

What seems to be the problem actually, is that you assume that the name/key passed as the stream is supposed to be appended to the version.
This is incorrect, as that is only meant to differentiate that stream from the other streams and nothing else.

What you need to do is to append the actual version as well, with either "-alpha, -beta, -current, -nightly, etc".
This could then update that json with the version you want (Do note though, that a non-prerelease is considered a higher version than a prerelease. So if the json says version `1.1.7.0`, then it won't get updated to `1.1.7.0-current`.)

**Side-Note:** Regarding the `Get-FixVersion` helper, I suggest that you also specify the `-OnlyFixBelowVersion` parameter, otherwise you may get unintended updates/versions than what you truly want.

**Comment by OlafHaag** [comment]
Thanks, for helping out! I got a few more questions though.

> What seems to be the problem actually, is that you assume that the name/key passed as the stream is supposed to be appended to the version.
> This is incorrect, as that is only meant to differentiate that stream from the other streams and nothing else.

I didn't assume that the stream's key should be appended to the version, I just chose the same name for the stream and as a pre-release marker. But I did assume that the version in the json should be the same as in the nuspec, which isn't the case.
The software vendor has 2 streams that they call *solid* and *current*, with *current* being the dev version (possibly unstable). But their versioning is continuous. On their part there's no -alpha or -current appended to the versions of that stream, so the pre-releases in the *current* stream would always take precedence over the solid stream if taken as is. That's why I added the *-current* to the version of that stream, so choco is marking it as a pre-release and users knowing the software would instantly see that these versions are from the possibly instable *current* stream.
 
> What you need to do is to append the actual version as well, with either "-alpha, -beta, -current, -nightly, etc".

Append the actual version where? To the keys of the streams? Otherwise I already appended the -current tag to the pre-release version in the value of the key, but the json isn't picking it up. I don't know where the json gets its version info from, but it doesn't seem to be from the values I set in the streams.

> **Side-Note:** Regarding the `Get-FixVersion` helper, I suggest that you also specify the `-OnlyFixBelowVersion` parameter, otherwise you may get unintended updates/versions than what you truly want.

Under which circumstances would I use this? It's an upper limit to what fix notation will be applied to? That upper limit seems to be arbitrarily chosen. I don't want to have to manually change that every so often.

**Comment by OlafHaag** [comment]
Okay, I think I found my error. The json that was present seemed to be from a test run where I didn't yet setup the versions as they are now. Deleting it and running again does indeed set the correct versions.

Now I only need to check, if appveyor pushes changes made to the json during update back to the github repo. The json gets updated, if a newer version come along, right?

**Comment by AdmiringWorm** [comment]
> That's why I added the -current to the version of that stream, so choco is marking it as a pre-release and users knowing the software would instantly see that these versions are from the possibly instable current stream.

Ah, sorry. I looked at the `update.ps1` script, but must have missed that you manually add `-current` to the version. Which is why I thought you maybe believed that the stream name would be appended to the version. Sorry about that.

> Under which circumstances would I use this? It's an upper limit to what fix notation will be applied to? That upper limit seems to be arbitrarily chosen. I don't want to have to manually change that every so often.

It is indeed an upper limit, while the limit is mostly towards a "stable" release, I can not guarantee that there won't be some kind of unknown parsing of the version without it.

The reason why I suggest using an upper limit though, is because there may be an incorrect version being outputted when it isn't specified (while I haven't figured out why this happens, nor am able to reproduce it in the module. I have seen it happen in with my own chocolatey packages.). So it is more a, better safe than sorry kind of thing.

> Okay, I think I found my error. The json that was present seemed to be from a test run where I didn't yet setup the versions as they are now. Deleting it and running again does indeed set the correct versions.

Glad you figured it out.

> Now I only need to check, if appveyor pushes changes made to the json during update back to the github repo. The json gets updated, when a newer version comes along, right?

As long as your json file is checked into the github repository before running it on appveyor, it will then also be checked in when it gets updated on the CI (everything in the package folder will be checked in during updates).

**Comment by OlafHaag** [comment]
Thanks a lot for the information, @AdmiringWorm !
