### ISSUE TITLE
Make updateall try to run config script first

### ISSUE THREAD

**Issue by Elderry** [majkinetor/au#40]
IMHO, `updateall` should firstly check if the file `$au_root/update_all.ps1` or `$au_root/../au/update_all.ps1` exists, and execute it if yes. Just like `update` does.

**Comment by majkinetor** [comment]
No, because there is a big difference between those functions. While `update` can not be run without `update.ps1` easily, I run `updateall` on its own (outside of script) all the time - it grabs current dir and executes it or parts of it, etc... It doesn't require plugins, so calls such as `updateall` or `updateall y* -Options ([ordered]@{Force = $true})` are quite frequent.
