### ISSUE TITLE
Allow specifying user-agent with Get-RemoteFiles

### ISSUE THREAD

**Issue by remleduff** [majkinetor/au#62]
I need the ability to specify the user-agent that is used to download files. With the default user-agent a server I'm using responds with "403: Forbidden".

The easiest way to do this is to add:
`$client.Headers.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)")` directly before `$client.DownloadFile(...)` in Get-RemoteFiles.ps1

It needs to be added before each invocation of DownloadFile, as it seems to only take effect for the following request. I'm not sure what the best way of specifying the agent as a parameter would be, but will happily use any solution.

**Comment by majkinetor** [comment]
`Get-RemoteFiles` is there to provide quick way for majority of packages. Its not good choice for some situations - headers, proxies etc.  For such cases it is expected that you implement downloader yourself.

This is ultimatelly something that should be implemented by chocolatey helper module but mentioned module still fails to provide reasonable and reusable proxy support (until recently headers were major problem too). Implementing complete and robust network downloader is out of scope of AU, otherwise it would quickly provide same functionality in that area as choco helper module function `Get-WebFile` and friends. I  would rather have people improve choco helpers and refactor proxy and header stuff in various functions (instead of current copy/paste) so AU can use it instead of reinventing the stuff but it might not be that easy to get such PR approved. 

Your best option is IMO to code it yourself for your particular need.

**Comment by abejenaru** [comment]
Hi, I'm running into the same problems - I would hope that proxy support has improved during last year? If not, I hope this issue gets more attention as AU become the recommended method to automate package maintenance :(

**Comment by majkinetor** [comment]
The original problem is with headers not with proxy.


>  I would hope that proxy support has improved during last year?

Somewhat, but for packages still not good, see Get-EffectiveProxy from coreteam extension for help. Or use my posh function `proxy` from my posh repo.
